// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bapyehgrrmmfiuxnxirp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcHllaGdycm1tZml1eG54aXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjQ3NTUsImV4cCI6MjA2ODc0MDc1NX0.HBvO53B4nyBXcy1x9u7mUeS5uAkur6rv6AerdSUJnbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});